print("input() pauses the program to take user text and assign it to a variable,input() takes one argument which is the prompt")
print("a prompt can also be a variable that stores a string")
x = 'please enter text : '
y = input(x)
print(f"this is your text : {y}")
print('one way to build a multiline string, is \nx = "xdc"\nx += "letroll"')
print('a for loop takes a collection of items and executes the block of code for each item')
print('in contrast a while loop runs as long as a statement evaluates to true')
print('a variable called a flag can be used to act as a signal for the program, program checks the value of the flag p.120')
print('break can be used to immediatly quit a loop without running the remainder of the loop block')
print('continue can be used to return to the start of a loop, usually after a condtitional test')
print("it's preferable to use a while loop while working with lists")
print("using while on a list while run the loop as long as the list isn't empty")
print('to remove all instances of a word from a list, list.remove(str) can be combined with while')
